### ISSUE TITLE
Can't use this editor

### ISSUE THREAD

**Issue by Strangefruit1233** [CoDkid2006/BoTN_Save_Editor#1]
Hi so im very new to this type of thing and I can't even manage to make the file work. I placed it into my directory but Im not sure how to "modify logic in main" sorry im so incompetent but could you help me out?

**Comment by CoDkid2006** [comment]
This editor requires programming experience to use. Guides may be written in the future but not planned.

**Comment by Strangefruit1233** [comment]
Alright thanks anyways.

**Comment by VRXZ** [comment]
Anymore new guides?
