### ISSUE TITLE
[Errno 2] No such file or directory: '0.sav'

### ISSUE THREAD

**Issue by hujo016** [CoDkid2006/BoTN_Save_Editor#3]
sorry to bother you if you thought this dead. i was attempting to use the editor and i cant figure out this error. i have the editor in the save folder(img provided).  im new to python so im not good at this nor do i know what to expect but when i run the file by double clicking it it does create the 0_.sav file but i then dont know where to input my commands to edit and i assume that is the wrong way to run it. here is the whole return i get. 
C:\Users\***>python C:\Users\***\AppData\Local\OBF\Saved\SaveGames\BoTN_Save_Editor-main\NephelymSaveEditor.py
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\OBF\Saved\SaveGames\BoTN_Save_Editor-main\NephelymSaveEditor.py", line 3873, in <module>
    NephelymSaveEditor(save_in).save(save_out)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Local\OBF\Saved\SaveGames\BoTN_Save_Editor-main\NephelymSaveEditor.py", line 3636, in __init__
    self.load(save_file)
  File "C:\Users\***\AppData\Local\OBF\Saved\SaveGames\BoTN_Save_Editor-main\NephelymSaveEditor.py", line 3703, in load
    save_data = self.load_save(file_in)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Local\OBF\Saved\SaveGames\BoTN_Save_Editor-main\NephelymSaveEditor.py", line 1079, in load_save
    with open(save_name, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^

<img width="326" alt="explorer_yToOQWRNtb" src="https://github.com/CoDkid2006/BoTN_Save_Editor/assets/146797947/c1133bce-00a3-42ad-b9ab-e919ad7b2ca0">

**Comment by CoDkid2006** [comment]
Hello, 

They way you ran it the image, it actually ran properly. The default behavior is to load the save file and to export it again to check that parsing is proper. the error you're seeing the second time is that the save files are not in the same folder as the script/the paths for the saves are not valid.

The editor is a programming based editor and not a gui based one, so you will need to code the changes you want to make.

Some examples can be found in the wiki on the [Examples Page](https://github.com/CoDkid2006/BoTN_Save_Editor/wiki/Examples). Additionally there are some examples already inside of the python script main function starting at line 3865.
